AgriDoktorum/AgriDoktorum.WebApp/Models/Entity/About.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AgriDoktorum.WebApp.Models.Entity
{
    public class About
    {
        public int Id { get; set; }
        public string AboutTitle { get; set; }
        public string AboutDescription { get; set; }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Models/Entity/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AgriDoktorum.WebApp.Models.Entity
{
    public class Contact
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string TelNo { get; set; }
        public string Email { get; set; }
        
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/AboutController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.EntityDb;
using AgriDoktorum.WebApp.Models.ViewModel.About;
using AgriDoktorum.WebApp.Models.ViewModel.PatientReference;

namespace AgriDoktorum.WebApp.Controllers
{
    [RoutePrefix("Hakkımda")]
    public class AboutController : Controller
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        // GET: About
        [Route]
        public ActionResult Index()
        {
            var patientReferences = _context.PatientReferences.Select(i =>
                new PatientReferenceViewModel()
                {
                    ReferenceName = i.ReferenceName,
                    ReferenceSurname = i.ReferenceSurname,
                    ReferenceRemark = i.ReferenceRemark,
                    ReferenceImage = i.ReferenceImage
                }); 
            
            var about = _context.About.Select(i =>
                new AboutViewModel()
                {
                    AboutTitle = i.AboutTitle,
                    AboutDescription = i.AboutDescription
                });

            var aboutIndexModel = new AboutIndexViewModel {AboutView = about, PatientReferenceView = patientReferences};

            return View(aboutIndexModel);
        }

        // GET: About/Edit/5
        [Auth]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            About about = _context.About.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        // POST: About/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Auth]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,AboutTitle,AboutDescription,AboutImage")] About about)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(about).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(about);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/AdminViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.EntityDb;

namespace AgriDoktorum.WebApp.Controllers
{
    [Auth]
    public class AdminViewController : Controller
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        // GET: AboutView
        public ActionResult AboutView()
        {
            return View(_context.About.ToList());
        }

        //GET : ContactView
        public ActionResult ContactView()
        {
            return View(_context.Contact);
        }

        //GET : BlogView
        public ActionResult BlogView()
        {
            return View(_context.Blogs);
        }

        //GET : TreatmentView
        public ActionResult TreatmentView()
        {
            return View(_context.Treatments);
        }

        //GET : GalleryView
        public ActionResult GalleryView()
        {
            return View(_context.Galleries);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.EntityDb;
using AgriDoktorum.WebApp.Models.ViewModel.Blog;

namespace AgriDoktorum.WebApp.Controllers
{
    public class BlogController : Controller
    {
        private readonly DatabaseContext db = new DatabaseContext();

        public ActionResult List(int? id, string q)
        {
            IQueryable<Blog> blog = db.Blogs;
            IQueryable<Blog> blogs = blog.OrderByDescending(p => p.ModifiedOn);

            if (id != null)
            {
                blogs = blogs.Where(i => i.CategoryId == id);
            }
            if (string.IsNullOrEmpty(q) == false)
            {
                blogs = blogs.Where(i => i.BlogTittle.Contains(q) || i.BlogDescription.Contains(q));
            }

            return View(blogs.ToList());
        }


        // GET: Blog
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var categories = db.Categories.ToList();

            if (pageSize > 50)
            {
                pageSize = 50;
            }

            IQueryable<Blog> query = db.Blogs;
            IQueryable<Blog> dataQuery = query.OrderByDescending(p => p.ModifiedOn).Skip((page - 1) * pageSize).Take(pageSize);

            int recordCount = query.Count();
            int pageCount = recordCount / pageSize;

            if (recordCount % pageSize > 0)
                pageCount++;

            return View(new BlogPostViewModel { GetBlogs = dataQuery.ToList(), PageCount = pageCount, CurrentPage = page });
        }

        // GET: Blog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blog/Create
        [Auth]
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryTitle");
            return View();
        }

        // POST: Blog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Auth]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BlogTittle,BlogText,BlogDescription,CategoryId,BlogImage,ModifiedUsername")] Blog blog, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var extension = Path.GetExtension(file.FileName);

                    if (extension == ".jpg" || extension == ".png")
                    {
                        var folder = Server.MapPath("/upload/Blog");
                        var randomfilename = Path.GetFileName(file.FileName);
                        var filename = Path.ChangeExtension(randomfilename, ".jpg");

                        blog.BlogImage = filename;

                        var path = Path.Combine(folder, filename);

                        file.SaveAs(path);
                    }
                    else
                    {
                        ViewData["message"] = "Resim dosyası seçiniz.";
                    }
                }
                else
                {
                    ViewData["message"] = "Bir dosya seçiniz";
                }
                blog.CreatedOn = DateTime.Now;
                blog.ModifiedOn = DateTime.Now;
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("BlogView","AdminView");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryTitle", blog.CategoryId);
            return View(blog);
        }

        // GET: Blog/Edit/5
        [Auth]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryTitle", blog.CategoryId);
            return View(blog);
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Auth]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,BlogTittle,BlogText,BlogDescription,CategoryId,ModifiedUsername")] Blog blog, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var extension = Path.GetExtension(file.FileName);

                    if (extension == ".jpg" || extension == ".png")
                    {
                        var folder = Server.MapPath("~/upload/Blog");
                        var randomfilename = Path.GetFileName(file.FileName);
                        var filename = Path.ChangeExtension(randomfilename, ".jpg");

                        blog.BlogImage = filename;

                        var path = Path.Combine(folder, filename);

                        file.SaveAs(path);
                    }
                    else
                    {
                        ViewData["message"] = "Resim dosyası seçiniz.";
                    }
                }
                else
                {
                    ViewData["message"] = "Bir dosya seçiniz";
                }
                blog.CreatedOn = DateTime.Now;
                blog.ModifiedOn = DateTime.Now;
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("BlogView", "AdminView");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryTitle", blog.CategoryId);
            return View(blog);
        }

        // GET: Blog/Delete/5
        [Auth]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [Auth]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("BlogView", "AdminView");
        }
        [Auth]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.EntityDb;

namespace AgriDoktorum.WebApp.Controllers
{
    [RoutePrefix("İletişim")]
    public class ContactController : Controller
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        // GET: Contact
        [Route]
        public ActionResult Index()
        {
            return View(_context.Contact.ToList());
        }

        // GET: Contact/Edit/5
        [Auth]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _context.Contact.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contact/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Auth]
        public ActionResult Edit([Bind(Include = "Id,Address,TelNo,Email")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(contact).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.EntityDb;

namespace AgriDoktorum.WebApp.Controllers
{
    [RoutePrefix("Galeri")]
    public class GalleryController : Controller
    {
        private readonly DatabaseContext db = new DatabaseContext();

        // GET: Gallery
        [Route]
        public ActionResult Index()
        {
            return View(db.Galleries.ToList());
        }

        // GET: Gallery/Create
        [Auth]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gallery/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,VideoUrl")] Gallery gallery)
        {
            if (ModelState.IsValid)
            {
                db.Galleries.Add(gallery);
                db.SaveChanges();
                return RedirectToAction("GalleryView", "AdminView");
            }

            return View(gallery);
        }

        // GET: Gallery/Edit/5
        [Auth]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Gallery/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,VideoUrl")] Gallery gallery)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gallery).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GalleryView", "AdminView");
            }
            return View(gallery);
        }

        // GET: Gallery/Delete/5
        [Auth]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = db.Galleries.Find(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Gallery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gallery gallery = db.Galleries.Find(id);
            db.Galleries.Remove(gallery);
            db.SaveChanges();
            return RedirectToAction("GalleryView", "AdminView");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Views/AdminView/AboutView.cshtml
@model IEnumerable<AgriDoktorum.WebApp.Models.Entity.About>
@{
    ViewBag.Title = "AboutView";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Hakkında</h2>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AboutTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AboutDescription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AboutTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutDescription)
            </td>
            <td>
                @if (item != null)
                {
                    @Html.ActionLink("Düzenle", "Edit", "About", new { id = item.Id }, new { @class = "btn btn-primary btn" })
                }
            </td>
        </tr>
    }

</table>

AgriDoktorum/AgriDoktorum.WebApp/Views/AdminView/BlogView.cshtml
@using AgriDoktorum.WebApp.Models.Entity
@model IEnumerable<Blog>
@{
    ViewBag.Title = "BlogView";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Blog</h2>

<p>
    @Html.ActionLink("Yeni Blog", "Create", "Blog")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogTittle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogImage)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogTittle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogImage)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Blog", new { id = item.Id }, new { @class = "btn btn-primary btn" })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Blog", new { id = item.Id }, new { @class = "btn btn-danger btn" })
            </td>
        </tr>
    }

</table>

AgriDoktorum/AgriDoktorum.WebApp/Views/AdminView/ContactView.cshtml
@using AgriDoktorum.WebApp.Models.Entity
@model IEnumerable<Contact>
@{
    ViewBag.Title = "ContactView";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>İletişim</h2>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TelNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Contact", new { id = item.Id }, new { @class = "btn btn-primary btn" })
            </td>
        </tr>
    }

</table>

AgriDoktorum/AgriDoktorum.WebApp/Views/AdminView/GalleryView.cshtml
@model IEnumerable<AgriDoktorum.WebApp.Models.Entity.Gallery>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Galeri</h2>

<p>
    @Html.ActionLink("Yeni Video", "Create","Gallery")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VideoUrl)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VideoUrl)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit","Gallery", new { id = item.Id }, new { @class = "btn btn-primary btn" })
            </td>
            <td>
                @Html.ActionLink("Sil", "Delete", "Gallery", new { id = item.Id }, new { @class = "btn btn-danger btn" })
            </td>
        </tr>
    }

</table>

AgriDoktorum/AgriDoktorum.WebApp/Views/AdminView/TreatmentView.cshtml
@using AgriDoktorum.WebApp.Models.Entity
@model IEnumerable<Treatment>
@{
    ViewBag.Title = "TreatmentView";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Tedavi Yöntemleri</h2>

<p>
    @Html.ActionLink("Yeni Tedavi Yöntemi", "Create", "Treatment")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TreatmentTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TreatmentText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TreatmentImage)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TreatmentTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TreatmentText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TreatmentImage)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Treatment", new { id = item.Id }, new { @class = "btn btn-primary btn" })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Treatment", new { id = item.Id }, new { @class = "btn btn-danger btn" })
            </td>
        </tr>
    }

</table>