AgriDoktorum/AgriDoktorum.WebApp/Models/ViewModel/Admin/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AgriDoktorum.WebApp.Models.ViewModel.Admin
{
    public class LoginViewModel
    {
        [DisplayName("Kullanıcı Adı"),
         Required(ErrorMessage = "{0} Alanı boş geçilemez"),
         StringLength(25, ErrorMessage = "{0} max. {1} Karakter olmalı")]
        public string Username { get; set; }

        [DisplayName("Şifre"),
         Required(ErrorMessage = "{0} Alanı boş geçilemez"),
         StringLength(25, ErrorMessage = "{0} max. {1} Karakter olmalı"),
         DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Models/ViewModel/Admin/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AgriDoktorum.WebApp.Models.ViewModel.Admin
{
    public class RegisterViewModel
    {
        [DisplayName("Kullanıcı Adı"),
         Required(ErrorMessage = "{0} Alanı boş geçilemez"),
         StringLength(25, ErrorMessage = "{0} max. {1} Karakter olmalı")]
        public string Username { get; set; }

        [DisplayName("Email"),
         Required(ErrorMessage = "{0} Alanı boş geçilemez"),
         StringLength(70, ErrorMessage = "{0} max. {1} Karakter olmalı"),
         EmailAddress(ErrorMessage = "{0} alanı için geçerli bir E-Posta adresi giriniz")]
        public string Email { get; set; }

        [DisplayName("Şifre"),
         Required(ErrorMessage = "{0} Alanı boş geçilemez"),
         DataType(DataType.Password),
         StringLength(25, ErrorMessage = "{0} max. {1} Karakter olmalı")]
        public string Password { get; set; }

        [DisplayName("Şifre Tekrar"),
         Required(ErrorMessage = "{0} Alanı boş geçilemez"),
         DataType(DataType.Password),
         StringLength(25, ErrorMessage = "{0} max. {1} Karakter olmalı"),
         Compare("Password", ErrorMessage = "{0} ile {1} uyuşmuyor")]
        public string RePassword { get; set; }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/SendMessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.EntityDb;

namespace AgriDoktorum.WebApp.Controllers
{
    public class SendMessagesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: SendMessages
        [Auth]
        public ActionResult Index()
        {
            return View(db.SendMessage.ToList());
        }

        // GET: SendMessages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SendMessages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PhoneNumber,Email,Name,Text")] SendMessage sendMessage)
        {
            if (ModelState.IsValid)
            {
                db.SendMessage.Add(sendMessage);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(sendMessage);
        }

        // GET: SendMessages/Delete/5
        [Auth]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SendMessage sendMessage = db.SendMessage.Find(id);
            if (sendMessage == null)
            {
                return HttpNotFound();
            }
            return View(sendMessage);
        }

        // POST: SendMessages/Delete/5
        [HttpPost, ActionName("Delete")]
        [Auth]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SendMessage sendMessage = db.SendMessage.Find(id);
            db.SendMessage.Remove(sendMessage);
            db.SaveChanges();
            return RedirectToAction("Index","Admin");
        }
        [Auth]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@{
    Html.RenderAction("Index","SendMessages");
}

AgriDoktorum/AgriDoktorum.WebApp/Views/Admin/Login.cshtml
@using AgriDoktorum.WebApp.Models.ViewModel.Admin
@model LoginViewModel
@{
    ViewBag.Title = "Giriş Sayfası";
    Layout = null;
}

@using (Html.BeginForm())
{
    <link href="~/Content/LoginRegister.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <!DOCTYPE html>
    <html>
    <head>
        <title>Login Page</title>
        <!--Made with love by Mutiullah Samim -->
        <!--Bootsrap 4 CDN-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!--Fontawesome CDN-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

        <!--Custom styles-->
        <link rel="stylesheet" type="text/css" href="styles.css">
    </head>
    <body>
        <div class="container">
            <div class="d-flex justify-content-center h-100">
                <div class="card">
                    <div class="card-header">
                        <h3>Giriş Yap</h3>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="input-group form-group">
                                @Html.ValidationSummary(false)
                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                @Html.TextBoxFor(model => model.Username, new { @class = "form-control", placeholder = "Kullanıcı Adı" })
                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                @Html.TextBoxFor(model => model.Password, new { @class = "form-control", placeholder = "Şifre", type = "password" })
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn float-right login_btn">Giriş Yap</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
}

AgriDoktorum/AgriDoktorum.WebApp/Views/Admin/Register.cshtml
@using AgriDoktorum.WebApp.Models.ViewModel.Admin
@model RegisterViewModel
@{
    ViewBag.Title = "Register";
    Layout = null;
}

@using (Html.BeginForm())
{
    <link href="~/Content/LoginRegister.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <!DOCTYPE html>
    <html>
    <head>
        <title>Login Page</title>
        <!--Made with love by Mutiullah Samim -->
        <!--Bootsrap 4 CDN-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!--Fontawesome CDN-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

        <!--Custom styles-->
        <link rel="stylesheet" type="text/css" href="styles.css">
    </head>
    <body>

        <div class="container">
            <div class="d-flex justify-content-center h-100">
                <div class="card">
                    <div class="card-header">
                        <h3>Giriş Yap</h3>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="input-group form-group">
                                @Html.ValidationSummary(false)
                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                @Html.TextBoxFor(model => model.Username, new { @class = "form-control", placeholder = "Kullanıcı Adı" })
                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "Email" })
                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                @Html.TextBoxFor(model => model.Password, new { @class = "form-control", placeholder = "Şifre", type = "password" })
                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                @Html.TextBoxFor(model => model.RePassword, new { @class = "form-control", placeholder = "Şifre(Tekrar)", type = "password" })
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn float-right login_btn">Giriş Yap</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

}