AgriDoktorum/AgriDoktorum.WebApp/Models/Entity/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AgriDoktorum.WebApp.Models.Entity
{
    public class Category
    {
        public int Id { get; set; }

        [Required, StringLength(50)]
        public string CategoryTitle { get; set; }

        [StringLength(150)]
        public string CategoryDescription { get; set; }

        public virtual List<Blog> Blogs { get; set; }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.EntityDb;

namespace AgriDoktorum.WebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly DatabaseContext db = new DatabaseContext();

        //GET : CategoryList
        public PartialViewResult CategoryList()
        {
            return PartialView(db.Categories.ToList());
        }

        // GET: Category
        [Auth]
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Category/Create
        [Auth]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Auth]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryTitle,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        [Auth]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Auth]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryTitle,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        [Auth]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [Auth]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Auth]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Views/Category/CategoryList.cshtml
@model IEnumerable<AgriDoktorum.WebApp.Models.Entity.Category>

@if (Model.Count() > 0)
{
    <aside class="single_sidebar_widget post_category_widget">
        <h4 class="widget_title">Kategoriler</h4>
        @foreach (var item in Model)
        {
            <ul class="list cat-list">
                <li>
                    <a href="/Blog/List/@item.Id" class="d-flex">
                        <p>@item.CategoryTitle</p>
                    </a>
                </li>
            </ul>
        }
    </aside>
}

AgriDoktorum/AgriDoktorum.WebApp/Views/Category/Create.cshtml
@model AgriDoktorum.WebApp.Models.Entity.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Kategori</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryTitle, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CategoryTitle, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CategoryDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index", "Category")
</div>

AgriDoktorum/AgriDoktorum.WebApp/Views/Category/Delete.cshtml
@model AgriDoktorum.WebApp.Models.Entity.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>SİLMEK İSTEDİĞİNİZDEN EMİN MİSİNİZ ?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryDescription)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Listeye Dön", "Index")
        </div>
    }
</div>

AgriDoktorum/AgriDoktorum.WebApp/Views/Category/Edit.cshtml
@model AgriDoktorum.WebApp.Models.Entity.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryTitle, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CategoryTitle, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CategoryDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

AgriDoktorum/AgriDoktorum.WebApp/Views/Category/Index.cshtml
@model IEnumerable<AgriDoktorum.WebApp.Models.Entity.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategori</h2>

<p>
    @Html.ActionLink("Yeni Kategori", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryDescription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryDescription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn" })
            </td>
        </tr>
    }

</table>