AgriDoktorum/AgriDoktorum.WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.BusinessLayer;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.Entity;
using AgriDoktorum.WebApp.Models.ViewModel.Admin;

namespace AgriDoktorum.WebApp.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        [Auth]
        public ActionResult Index()
        {
            return View();
        }

        //GET : Login
        public ActionResult Login()
        {
            return View();
        }

        //POST : Login
        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                AdminManager adminManager = new AdminManager();
                BusinessLayerResult<AdUser> layerResult = adminManager.LoginUser(model);

                if (layerResult.ErrorList.Count > 0)
                {
                    layerResult.ErrorList.ForEach(x => ModelState.AddModelError("", x));
                    return View(model);
                }

                Session["user"] = layerResult.Result;
                return RedirectToAction("Index");
            }

            return View();
        }

        //GET : Register
        [Auth]
        public ActionResult Register()
        {
            return View();
        }

        //POST : Register
        [HttpPost]
        [Auth]
        public ActionResult Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var adminManager = new AdminManager();
                BusinessLayerResult<AdUser> uResult = adminManager.RegisterUser(model);

                if (uResult.ErrorList.Count > 0)
                {
                    uResult.ErrorList.ForEach(x => ModelState.AddModelError("", x));
                    return View(model);
                }

                return RedirectToAction("Login");
            }
            return View(model);
        }
        [Auth]
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Controllers/AdminViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgriDoktorum.WebApp.Filter;
using AgriDoktorum.WebApp.Models.EntityDb;

namespace AgriDoktorum.WebApp.Controllers
{
    [Auth]
    public class AdminViewController : Controller
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        // GET: AboutView
        public ActionResult AboutView()
        {
            return View(_context.About.ToList());
        }

        //GET : ContactView
        public ActionResult ContactView()
        {
            return View(_context.Contact);
        }

        //GET : BlogView
        public ActionResult BlogView()
        {
            return View(_context.Blogs);
        }

        //GET : TreatmentView
        public ActionResult TreatmentView()
        {
            return View(_context.Treatments);
        }

        //GET : GalleryView
        public ActionResult GalleryView()
        {
            return View(_context.Galleries);
        }
    }
}

AgriDoktorum/AgriDoktorum.WebApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AdminPanel", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "AboutView", "AdminView", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Contact", "ContactView", "AdminView", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("PatientReference", "Index", "PatientReference", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Gallery", "GalleryView", "AdminView", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Treatment", "TreatmentView", "AdminView", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Blog", "BlogView", "AdminView", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Category", "Index", "Category", null, new { @class = "navbar-link" })</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/Admin/Logout">
                            <span class="glyphicon glyphicon-log-out"></span> Logout
                        </a>

                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AgriDoktorum/AgriDoktorum.WebApp/Views/Shared/_Search.cshtml
@using (Html.BeginForm("List", "Blog", FormMethod.Get))
{
    <div class="well">
        <h4>Blog Arama</h4>
        <hr />
        <div class="input-group">
            @Html.TextBox("q", null, new { @class = "form-control" })
            <span class="input-group-append">
                <button class="btn" type="submit">
                    <span class="ti-search"></span>
                </button>
            </span>
        </div>
    </div>

}